#!/usr/bin/env bash

# Author: Jason Mumbulla (jasonmumbulla@gmail.com)
APPNAME="BiodiverseGUI"

DIR="$(cd "$(dirname "$0")" && pwd -P)"

# Create the log file directory if it doesn't exist
LOG_FILE="$HOME/Library/Logs/$APPNAME/$APPNAME.log"
mkdir -p "`dirname \"$LOG_FILE\"`"

# Run the app and redirect standard 
# output and error to the log file.
exec $DIR/$APPNAME >> $LOG_FILE 2>&1
