#!/bin/sh
# Author: Jason Mumbulla (jasonmumbulla@gmail.com)

APPNAME="BiodiverseGUI"

DIR=$(cd "$(dirname "$0")"; pwd)

# Create the log file directory if it doesn't exist
LOG_FILE="$HOME/Library/Logs/$APPNAME/$APPNAME.log"
mkdir -p "`dirname \"$LOG_FILE\"`"

#echo "$(date +%b\ %d\ %H:%M:%S) $(hostname)[(echo $$) $APPNAME:" >>"$LOG_FILE"
#echo "$(date +%b\ %d\ %H:%M:%S) $(hostname)[$(echo $$)] $APPNAME: BiodiverseGUI_EXEC: $BiodiverseGUI_EXEC" >>"$LOG_FILE"
echo "$(date +%b\ %d\ %H:%M:%S) $(hostname)[$(echo $$)] $APPNAME: "\$DIR/\$APPNAME": "$DIR/$APPNAME"" >>"$LOG_FILE"

# Run the app and redirect standard 
# output and error to the log file.
exec $DIR/$APPNAME >> $LOG_FILE 2>&1
