use strict;
use warnings;
use 5.010;

use Carp;
use English qw { -no_match_vars };

use Biodiverse::BaseData;

my $bd_file  = shift @ARGV;
my $out_file = shift @ARGV;
my $runs     = shift @ARGV // 100;
my $index    = shift @ARGV // 'S2';
my $prng_starting_seed = shift @ARGV // time;
my $prng_seed_offset = shift @ARGV // 100;

croak "no basedata file specified" if !defined $bd_file;

my $bd = Biodiverse::BaseData->new(file => $bd_file);

my $prng_seed = int $prng_starting_seed;

$bd_file =~ /(.+)(\.bd.$)/;
my $prefix = "${1}_clusters_${runs}";
my $suffix = $2;

my $out_bd = $prefix . $suffix;

my $fname = $out_file // $prefix . '.newicks';
open my $fh, '>', $fname or croak "cannot open $fname";

say {$fh} "#NEXUS\n\nBegin trees;\n\n";
say {$fh} "[Generated by a $index clustering of $bd_file]";


for my $i (1 .. $runs) {
    my $name = sprintf "cluster_%04i", $i;
    my $cl = $bd->add_cluster_output(name => $name);
    $cl->run_analysis (
        index     => $index,
        prng_seed => $prng_seed,
    );
    #$bd->save (filename => $out_bd);
    #
    #if ($i == 1) {
    #    #  export to nexus format
    #    $cl->export (format => 'nexus', file => undef);  #  fixme fixme - use this to have a names block
    #}
    #else {
        #  export the rest to newick so they can be copied and pasted into the nexus file
        my $nwk = $cl->to_newick(use_internal_names => 0);
        say { $fh } "tree $name = ", $nwk, ';';
    #}

    $bd->delete_all_outputs (output => $cl);
    $prng_seed += $prng_seed_offset;
}

say {$fh} "End;\n\n";

